# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle Daemon.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
org.gradle.parallel=true

# Enable caching between builds.
org.gradle.caching=true

# AndroidX Jetpack libraries mapping.
android.useAndroidX=true

# Automatically convert third-party libraries to use AndroidX.
android.enableJetifier=true

# Set Java path to Java 21 explicitly for consistent compilation across environments.
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
